blueprint:
  name: Aqara Wireless Switch (single, double, hold, release)
  description: 'Control anything using Aqara Wireless Switch.
    Customizable actions for each press.
    This version of the blueprint is for buttons supporting single, double, hold and
    release actions. '
  domain: automation
  input:
    action_sensor:
      name: Action Sensor
      description: Zigbee2mqtt action sensor
      selector:
        entity:
          integration: mqtt
          domain: sensor
          multiple: false
    press_single:
      name: Single button press
      description: Action to run on single button press
      default: []
      selector:
        action: {}
    press_double:
      name: Double button press
      description: Action to run on double button press
      default: []
      selector:
        action: {}
    press_hold:
      name: Button hold
      description: Action to run on hold
      default: []
      selector:
        action: {}
    press_release:
      name: Button release
      description: Action to run on release
      default: []
      selector:
        action: {}
mode: restart
max_exceeded: silent
trigger:
  platform: state
  entity_id: !input action_sensor
condition:
- condition: template
  value_template: '{{ (trigger.to_state.attributes.action if trigger.to_state.state == ""
      else trigger.to_state.state) in ("single","double","hold","release")
    }}'
action:
- variables:
    command: '{{ trigger.to_state.attributes.action if trigger.to_state.state == ""
      else trigger.to_state.state }}'
- choose:
  - conditions:
    - '{{ command == ''single'' }}'
    sequence: !input press_single
  - conditions:
    - '{{ command == ''double'' }}'
    sequence: !input press_double
  - conditions:
    - '{{ command == ''hold'' }}'
    sequence: !input press_hold
  - conditions:
    - '{{ command == ''release'' }}'
    sequence: !input press_release